#! /usr/bin/env bash
# Shows the power menu
declare -r config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/wofi/power_menu"

# Menu options
declare -a menu=(
  "img:${config_dir}/log-out.svg:text:Log Out"
  "img:${config_dir}/reboot.svg:text:Reboot"
  "img:${config_dir}/shutdown.svg:text:Shutdown"
)

# Actions shuld be in the same index as it's menu option
declare -a actions=(
  "hyprctl dispatch exec uwsm stop"
  "reboot"
  "poweroff"
)

command_menu=$(
  IFS=$'\n'
  echo "${menu[*]}"
)
selected=$(
  echo -e "$command_menu" |
    run_or_close wofi \
      --show dmenu \
      --normal-window \
      --allow-images \
      --conf "${config_dir}/power_menu.conf" \
      --style "${config_dir}/power_menu.css" \
      --cache-file /dev/null
)
for i in "${!menu[@]}"; do
  if [[ "$selected" == "${menu[i]}" ]]; then
    ${actions[i]}
  fi
done
